version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      #- ./modules/module-start:/var/www/html/app/code/Shippify/LivePanel
      - ./modules/shippify-magento-2:/var/www/html/app/code/Shippify/ShippifyMagento
      #- ./modules/ExampleAdminNewPage:/var/www/html/app/code/MyCompany/ExampleAdminNewPage
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  db-data: 